import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import styled from 'styled-components';
import samImg from "public/SamMcKay.jpg";
import Dropdown from "/components/Dropdown";
import React, {useState} from 'react';
import algeria from "../Outlines/Algeria.png";

const Hero = styled.div`
  height: 50vh;
  display: flex;
  justify-content: start;
  align-items: flex-start;
  background: #202733;
  `

const StyledButton = styled.button`
  font-size: 15px;
  background-color: #202733;
  margin-left: 40%;
  border-color: #fff;
  width: 20%;
  height: 10%;
  border-radius: 5px;
  margin-bottom: 3%;
`

const StyledText = styled.p`
  margin-left: 10%;
  font-size: 15px;
  max-width: 80%;

`

const StyledImage = styled.img`
  height: 200px;
  width: 250px;
  margin-top: 10%;
  margin-bottom: 2%;
  postion: static;
  margin-left: 42%;
  display: block;
`
const CountryImages = [
  "https://i.imgur.com/ciapi9a.png", "https://i.imgur.com/ZGe8qpm.png", "https://i.imgur.com/xRQBZCF.png", "https://i.imgur.com/VSY7UGC.png", "https://i.imgur.com/antwu0T.png", "https://i.imgur.com/OeedMq1.png", "https://i.imgur.com/gB8g5Pe.png", "https://i.imgur.com/gFDdANR.png", "https://i.imgur.com/9ma69QZ.png", "https://i.imgur.com/Fv9Oy8T.png", "https://i.imgur.com/nPHeogp.png", "https://i.imgur.com/JGKu4l4.png", "https://i.imgur.com/AafZLgR.png", "https://i.imgur.com/UpQ4C6M.png", "https://i.imgur.com/rwbGZTF.png", "https://i.imgur.com/kb4q4Yx.png", "https://i.imgur.com/FoZ4ANh.png"
]


const options = [
  { value: "Algeria", label: "Algeria" }, 
  { value: "Angola", label: "Angola"},
  { value: "Benin", label: "Benin"},
  { value: "Botswana", label: "Botswana"},
  { value: "Burkina Faso", label: "Burkina Faso"},
  { value: "Cape Verde", label: "Cape Verde"},
  { value: "Central African Republic", label: "Central African Republic"},
  { value: "Chad", label: "Chad"},
  { value: "Comoros", label: "Comoros"},
  { value: "Djibouti", label: "Djibouti"},
  { value: "Democratic Republic of the Congo", label: "Democratic Republic of the Congo"},
  { value: "Egypt", label: "Egypt"},
  { value: "Equatorial Guinea", label: "Equatorial Guinea"},
  { value: "Eritrea", label: "Eritrea"},
  { value: "Ivory Coast", label: "Ivory Coast"},
  { value: "Mali", label: "Mali"},
  { value: "Sao Tome and Principe", label: "Sao Tome and Principe"}
]

export default function Home() {
  let i = Math.random() * (16 - 0) + 0;
  const [imageSrc, setImageSrc] = useState(encodeURIComponent(CountryImages[i]));

  const handleClick = () => {
    i = Math.random() * (16 - 0) + 0;
    setImageSrc(CountryImages[i]);
  };

  return (
    <>
      <Head>
          <title>GeoPursuit | Video Games as an Educational Medium</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <StyledImage src={imageSrc} alt="example"/>
      </Hero>
      <Hero style={{height: "10vh"}}>
        <Dropdown isSearchable placeHolder="Select..." options={options}/>
      </Hero>
      <Hero>
        <StyledButton onClick={handleClick}><StyledText>Submit Answer</StyledText></StyledButton>
      </Hero>
    </>
  );
}
