import Head from 'next/head';
import Image from 'next/image';
import styles from '@/styles/Home.module.css';
import styled from 'styled-components';
import samImg from "public/SamMcKay.jpg";
import Dropdown from "/components/Dropdown";

const Hero = styled.div`
  height: 50vh;
  display: flex;
  justify-content: start;
  align-items: flex-start;
  background: #202733;
  `

const StyledButton = styled.button`
  font-size: 15px;
  background-color: #202733;
  margin-left: 40%;
  border-color: #fff;
  width: 20%;
  height: 10%;
  border-radius: 5px;
  margin-bottom: 3%;
`

const StyledText = styled.p`
  margin-left: 10%;
  font-size: 15px;
  max-width: 80%;

`

const StyledImage = styled.img`
  height: 200px;
  width: 250px;
  margin-top: 5%;
  margin-bottom: 2%;
  postion: static;
  margin-left: 40%;
  display: block;
`

const options = [
  { value: "Algeria", label: "Algeria" }, 
  { value: "Angola", label: "Angola"},
  { value: "Benin", label: "Benin"},
  { value: "Botswana", label: "Botswana"},
  { value: "Burkina Faso", label: "Burkina Faso"},
  { value: "Burundi", label: "Burundi"},
  { value: "Cameroon", label: "Cameroon"},
  { value: "Cabo Verde", label: "Cabo Verde"},
  { value: "Central African Republic", label: "Central African Republic"},
  { value: "Chad", label: "Chad"},
  { value: "Comoros", label: "Comoros"},
  { value: "Côte dIvoire", label: "Côte dIvoire"},
  { value: "Democratic Republic of the Congo", label: "Democratic Republic of the Congo"},
  { value: "Djibouti", label: "Djibouti"},
  { value: "Egypt", label: "Egypt"},
  { value: "Equatorial Guinea", label: "Equatorial Guinea"},
  { value: "Eritrea", label: "Eritrea"},
  { value: "Eswatini", label: "Eswatini"},
  { value: "Ethiopia", label: "Ethiopia"},

]

export default function Home() {
  return (
    <>
      <Head>
          <title>GeoPursuit | Video Games as an Educational Medium</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <StyledImage src = "/Outlines/Algeria.png"/>
      </Hero>
      <Hero style={{height: "10vh"}}>
        <Dropdown isSearchable placeHolder="Select..." options={options}/>
      </Hero>
      <Hero>
        <StyledButton><StyledText>Submit Answer</StyledText></StyledButton>
      </Hero>
    </>
  )
}
