import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import styled from 'styled-components';
import React, { useState, useEffect } from 'react';
import dynamic from 'next/dynamic'; // import dynamic
import 'leaflet/dist/leaflet.css';

const Hero = styled.div`
  height: 80vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: #fff;
`;

const Heading = styled.h1`
  color: #000;
  font-size: 6rem;
  font-weight: 900;
`;


const HeroButton = styled.button`
  font-size: 1em;
  text-transform: uppercase;
  letter-spacing: .1em;
  background-color: rgba(0,0,0,0.0);
  border-radius: 100px;
  border: 3px solid #40F2FE;
  margin-left: 60em;
  margin-top: 10em;
  height: 60px;
  width: 200px;
  transition: all .3s;
  box-shadow: 0px 0px 20px rgba(202,152,254,0.5);

  &:hover {
    transform: scale(1.03);
    box-shadow: 0px 0px 20px rgba(202,152,254,1);
  }
`

const StyledLink = styled.a`
	padding: 0rem 2rem;
	color: #E6E1FC;
  margin-left: 60em;
`

// Use dynamic import to load MapContainer on the client-side
const MapContainer = dynamic(() => import('react-leaflet').then(module => module.MapContainer), {
  ssr: false
});
const TileLayer = dynamic(() => import('react-leaflet').then(module => module.TileLayer), {
  ssr: false
});

const Map = dynamic(() => import('react-leaflet').then(module=>module.Map), {
  ssr: false
});



export default function group1() {
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    if (TileLayer) {
      setIsLoaded(true);
    }
  }, [TileLayer]);

  if (!isLoaded) {
    return <div>Loading...</div>;
  }
  return (
    <>
      <Head>
        <title>Group1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
     integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
     crossorigin=""/>
      <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
     integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
     crossorigin=""></script>
      <script  src="./leaflet/dist/leaflet.js"></script>
      <script src="js/main.js"></script>
      </Head>
      <StyledLink href="/test"><HeroButton>Next</HeroButton></StyledLink>
      <div id="map">
        <MapContainer id="MapContainer" center={[7.1881, 21.0938]} zoom={3} attributionControl={false}>
          <TileLayer style="z-index:1" url="https://stamen-tiles-{s}.a.ssl.fastly.net/toner/{z}/{x}/{y}{r}.png" />
        </MapContainer>
      </div>
    </>
  );
};