import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import styled from 'styled-components';
import React, { useState, useEffect } from 'react';
import dynamic from 'next/dynamic'; // import dynamic
import 'leaflet/dist/leaflet.css';

const Hero = styled.div`
  height: 80vh;
  display: flex;
  justify-content: center;
  align-items: center;
  background: #fff;
`;

const Heading = styled.h1`
  color: #000;
  font-size: 6rem;
  font-weight: 900;
`;

// Use dynamic import to load MapContainer on the client-side
const MapContainer = dynamic(() => import('react-leaflet').then(module => module.MapContainer), {
  ssr: false
});
const TileLayer = dynamic(() => import('react-leaflet').then(module => module.TileLayer), {
  ssr: false
});

export default function group1() {
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    if (TileLayer) {
      setIsLoaded(true);
    }
  }, [TileLayer]);

  if (!isLoaded) {
    return <div>Loading...</div>;
  }
  return (
    <>
      <Head>
        <title>Group1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.3/dist/leaflet.css"
     integrity="sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI="
     crossorigin=""/>
      <script src="https://unpkg.com/leaflet@1.9.3/dist/leaflet.js"
     integrity="sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM="
     crossorigin=""></script>
      <script  src="./leaflet/dist/leaflet.js"></script>
      <script src="js/main.js"></script>
      </Head>
      <div id="map">
        <MapContainer id="MapContainer" center={[7.1881, 21.0938]} zoom={2}>
          <TileLayer style="z-index:0" url="https://stamen-tiles-{s}.a.ssl.fastly.net/toner/{z}/{x}/{y}{r}.png" />
        </MapContainer>
      </div>
    </>
  );
};