import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import styled from 'styled-components'

const Hero = styled.div`
  height: 80vh;
  display: flex;
  justify-content: start;
  align-items: flex-start;
  background: #202733;`

  const Heading = styled.h1`
    color: #fff;
    font-size: 6rem;
    font-weight: 900;`

  const Heading2 = styled.h2`
    color: #fff;
    font-size: 30px;
    font-weight: 500;
    margin-left: 3%;
    margin-top: 2%;
    display: block;
  `

const StyledButton = styled.button`
  font-size: 15px;
  font-weight: 20px;
  background-color: #2b3547;
  border-radius: 5px;
  margin-left: 2%;
  margin-top: 4%;
  border-color: #2b3547;
  width: 10%;
  height: 10%;
`

export default function Home() {
  return (
    <>
      <Head>
          <title>GeoPursuit | Video Games as an Educational Medium</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <Heading2>What group are you in?</Heading2>
      <StyledButton><a>Group 1</a></StyledButton>
      <StyledButton><a>Group 2</a></StyledButton>
      <StyledButton><a>Group 3</a></StyledButton>
        <Heading2>Introduction:{"\n"}</Heading2>
      </Hero>
    </>
  )
}
