import Head from 'next/head';
import styled from 'styled-components';
import React, {useState, useEffect} from 'react';
import Dropdown from '@/components/Dropdown';
import {e} from "../components/Dropdown";

const Hero = styled.div`
  height: 50vh;
  display: flex;
  justify-content: start;
  align-items: flex-start;
  background: #202733;
  `

const StyledButton = styled.button`
  font-size: 15px;
  background-color: #202733;
  margin-left: 40%;
  border-color: #fff;
  width: 20%;
  height: 10%;
  border-radius: 5px;
  margin-bottom: 3%;
`

const StyledText = styled.p`
  margin-left: 10%;
  font-size: 15px;
  max-width: 80%;

`

const StyledImage = styled.img`
  height: 200px;
  width: 250px;
  margin-top: 10%;
  margin-bottom: 2%;
  postion: static;
  margin-left: 42%;
  display: block;
`


const options = [
  { value: " Algeria", label: "Algeria" }, 
  { value: " Angola", label: "Angola"},
  { value: " Benin", label: "Benin"},
  { value: " Botswana", label: "Botswana"},
  { value: " Burkina Faso", label: "Burkina Faso"},
  { value: " Cape Verde", label: "Cape Verde"},
  { value: " Central African Republic", label: "Central African Republic"},
  { value: " Chad", label: "Chad"},
  { value: " Comoros", label: "Comoros"},
  { value: " Djibouti", label: "Djibouti"},
  { value: " Democratic Republic of the Congo", label: "Democratic Republic of the Congo"},
  { value: " Egypt", label: "Egypt"},
  { value: " Equatorial Guinea", label: "Equatorial Guinea"},
  { value: " Eritrea", label: "Eritrea"},
  { value: " Ivory Coast", label: "Ivory Coast"},
  { value: " Mali", label: "Mali"},
  { value: " Sao Tome and Principe", label: "Sao Tome and Principe"}
]

const countryOrder = ["Mali", "Chad", "Burkina", "Eritrea", "Central African Republic", "Angola", "Benin", "Cape Verde", "Democratic Republic of Congo", "Botswana", "Ivory Coast", "Algeria", "Egypt", "Equatorial Guinea", "Comoros", "Sao Tome", "Djibouti"];

var userScore = [];
var userChoice = [];

let i = 0;
export default function Game() {
  const [timeOnPage, setTimeOnPage] = useState(0);

  var CountryImages = [
    "https://i.imgur.com/kb4q4Yx.png",
    "https://i.imgur.com/gFDdANR.png",
    "https://i.imgur.com/antwu0T.png",
    "https://i.imgur.com/UpQ4C6M.png",
    "https://i.imgur.com/gB8g5Pe.png",
    "https://i.imgur.com/ZGe8qpm.png",
    "https://i.imgur.com/xRQBZCF.png",
    "https://i.imgur.com/OeedMq1.png",
    "https://i.imgur.com/nPHeogp.png",
    "https://i.imgur.com/VSY7UGC.png",
    "https://i.imgur.com/rwbGZTF.png",
    "https://i.imgur.com/ciapi9a.png",
    "https://i.imgur.com/JGKu4l4.png",
    "https://i.imgur.com/AafZLgR.png",
    "https://i.imgur.com/9ma69QZ.png",
    "https://i.imgur.com/FoZ4ANh.png",
    "https://i.imgur.com/Fv9Oy8T.png"
  ]
  const [imageSrc, setImageSrc] = useState(CountryImages[0]);

  useEffect(() => {
    const intervalId = setInterval(() => {
      setTimeOnPage(timeOnPage => timeOnPage + 1);
    }, 1000);

    return () => {
      clearInterval(intervalId);
    };
  }, []);


  const handleClick = () => {
    i+=1;

    setImageSrc(CountryImages[i]);
    if (e == countryOrder[i]) {
      userScore.push(true);
      userChoice.push(e);
    } else {
      userScore.push(false);
      userChoice.push(e);
    }
    
    if (i == 17) {
      if (typeof window !== 'undefined') {
        const finalScore = userScore;
        const finalChoices = userChoice;
        window.localStorage.setItem("userTime", timeOnPage);
        window.localStorage.setItem("userScore", finalScore);
        window.localStorage.setItem("userChoices", finalChoices);
        window.location.href = "/results";
      }
    }
  };

  return (
    <>
      <Head>
          <title>GeoPursuit | Video Games as an Educational Medium</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <StyledImage src={imageSrc} alt="example"/>
      </Hero>
      <Hero style={{height: "10vh"}}>
        <Dropdown isSearchable placeHolder="Select A Country" options={options}/>
      </Hero>
      <Hero>
        <StyledButton onClick={handleClick}><StyledText>Submit Answer</StyledText></StyledButton>
      </Hero>
    </>

);
}
